package application;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.MenuBar;

import javafx.scene.control.MenuItem;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.Menu;

import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;

public class TablasController implements Initializable {
	@FXML
	private TableView<Vuelo> datosTabla;
	@FXML
	private MenuBar MenuUp;
	@FXML
	private Menu MenuAerolinea;
	@FXML
	private MenuItem opcion1;
	@FXML
	private Menu MenuAvion;
	@FXML
	private MenuItem opcion2;
	@FXML
	private Menu MenuCiudad;
	@FXML
	private MenuItem opcion3;
	@FXML
	private TableColumn <Vuelo, String>IdNumeroVuelo;
	@FXML
	private TableColumn <Vuelo, String> IdOrigenVuelo;
	@FXML
	private TableColumn <Vuelo, String> IdDestinoVuelo;
	@FXML
	private TableColumn <Vuelo, String> IdCodigoAvion;
	@FXML
	private Button IdBtnAgregar;
	@FXML
	private TextField IdTxtNumero;
	@FXML
	private TextField IdTxtOrigen;
	@FXML
	private TextField idTxtDestino;
	@FXML
	private TextField idTxtCodigoAvion;
	
	private ObservableList<Vuelo>datos;

	// Event Listener on Button[#IdBtnAgregar].onMouseClicked
	@FXML
	public void ClicAgregar(MouseEvent event) {
		// TODO Autogenerated
		
		datos.add(new Vuelo(IdTxtNumero.getText(),IdTxtOrigen.getText(),idTxtDestino.getText(),idTxtCodigoAvion.getText()));
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
		this.datos = FXCollections.observableArrayList(new Vuelo("911", "Bogotá", "Medellin", "0001220"));
		
	IdNumeroVuelo.setCellValueFactory(new PropertyValueFactory<Vuelo, String>("numero"));
	IdNumeroVuelo.setCellValueFactory(new PropertyValueFactory<Vuelo, String>("origen"));
	IdNumeroVuelo.setCellValueFactory(new PropertyValueFactory<Vuelo, String>("destino"));
	IdNumeroVuelo.setCellValueFactory(new PropertyValueFactory<Vuelo, String>("codigo_Avion"));
	datosTabla.setItems(datos);	
	}
	
}
