package application;

import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.MenuBar;

import javafx.scene.control.MenuItem;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.Menu;

import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;

public class TablasController implements Initializable {
	@FXML
	private TableView datosTabla;
	@FXML
	private MenuBar MenuUp;
	@FXML
	private Menu MenuAerolinea;
	@FXML
	private MenuItem opcion1;
	@FXML
	private Menu MenuAvion;
	@FXML
	private MenuItem opcion2;
	@FXML
	private Menu MenuCiudad;
	@FXML
	private MenuItem opcion3;
	@FXML
	private TableColumn IdNumeroVuelo;
	@FXML
	private TableColumn  IdOrigenVuelo;
	@FXML
	private TableColumn  IdDestinoVuelo;
	@FXML
	private TableColumn  IdCodigoAvion;
	@FXML
	private Button IdBtnAgregar;
	@FXML
	private TextField IdTxtNumero;
	@FXML
	private TextField IdTxtOrigen;
	@FXML
	private TextField idTxtDestino;
	@FXML
	private TextField idTxtCodigoAvion;
	
	ObservableList<Vuelo>datos = FXCollections.observableArrayList();
	
	Datos data;

	// Event Listener on Button[#IdBtnAgregar].onMouseClicked
	@FXML
	public void ClicAgregar(MouseEvent event) {
		// TODO Autogenerated
		
		LinkedList<Vuelo> data1 = data.getDatos();
		for (Vuelo a: data1) {
			this.datos.add(a);
		}
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	this.data = new Datos();
	this.IdCodigoAvion.setCellValueFactory(new PropertyValueFactory ("codAvion"));
	this.IdDestinoVuelo.setCellValueFactory(new PropertyValueFactory ("destino"));
	this.IdOrigenVuelo.setCellValueFactory(new PropertyValueFactory ("origen"));
	this.IdNumeroVuelo.setCellValueFactory(new PropertyValueFactory ("numero"));
	datosTabla.setItems(this.datos);
	
	}
	
}
