package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.MenuBar;

import javafx.scene.control.MenuItem;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.Menu;

import javafx.scene.control.TableColumn;

public class TablasController {
	@FXML
	private MenuBar MenuUp;
	@FXML
	private Menu MenuAerolinea;
	@FXML
	private MenuItem opcion1;
	@FXML
	private Menu MenuAvion;
	@FXML
	private MenuItem opcion2;
	@FXML
	private Menu MenuCiudad;
	@FXML
	private MenuItem opcion3;
	@FXML
	private TableColumn IdNumeroVuelo;
	@FXML
	private TableColumn IdOrigenVuelo;
	@FXML
	private TableColumn IdDestinoVuelo;
	@FXML
	private TableColumn IdCodigoAvion;
	@FXML
	private Button IdBtnAgregar;
	@FXML
	private TextField IdTxtNumero;
	@FXML
	private TextField IdTxtOrigen;
	@FXML
	private TextField idTxtDestino;
	@FXML
	private TextField idTxtCodigoAvion;

	// Event Listener on Button[#IdBtnAgregar].onMouseClicked
	@FXML
	public void ClicAgregar(MouseEvent event) {
		// TODO Autogenerated
	}
}
